name: Check & Version File

permissions:
  contents: write   # <— wichtig für git push

on:
  schedule:
    - cron: "0 * * * *"   # stündlich
  workflow_dispatch:        # manuell startbar

jobs:
  fetch:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          persist-credentials: true
          fetch-depth: 0

      - name: Download file
        run: |
          mkdir -p fixtures
          curl -fSL "https://www.football-data.co.uk/fixtures.csv" -o fixtures/fixtures.csv

      - name: Commit if changed
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"

          if [ -n "$(git status --porcelain)" ]; then
            DATE=$(date -u +'%Y-%m-%d')
            cp fixtures/fixtures.csv fixtures/${DATE}_fixtures.csv

            git add fixtures/fixtures.csv fixtures/${DATE}_fixtures.csv
            git commit -m "Auto-update: ${DATE}"
            git push
          else
            echo "No changes ✅"
          fi
